// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_access_token_api_v1_login_access_token_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_login_access_token_api_v1_login_access_token_post'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IconsObjectSchema = {
    type: 'string',
    enum: [
        '/src/object',
        '/src/person',
        '/src/bike',
        '/src/scooter',
        '/src/bus',
        '/src/car',
        '/src/tractor',
        '/src/harvester',
        '/src/airplane'
    ],
    title: 'IconsObject'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token'
} as const;

export const TrackingObjectCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            type: 'string',
            maxLength: 255,
            title: 'Description'
        },
        icon_object: {
            $ref: '#/components/schemas/IconsObject',
            default: '/src/object'
        }
    },
    type: 'object',
    required: [
        'name',
        'description'
    ],
    title: 'TrackingObjectCreate'
} as const;

export const TrackingObjectPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            type: 'string',
            maxLength: 255,
            title: 'Description'
        },
        icon_object: {
            $ref: '#/components/schemas/IconsObject',
            default: '/src/object'
        },
        signal: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Signal'
        },
        position_lat: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 90,
                    minimum: -90
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position Lat'
        },
        position_lon: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 180,
                    minimum: -180
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position Lon'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'description',
        'signal',
        'position_lat',
        'position_lon'
    ],
    title: 'TrackingObjectPublic'
} as const;

export const TrackingObjectUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            type: 'string',
            maxLength: 255,
            title: 'Description'
        },
        icon_object: {
            $ref: '#/components/schemas/IconsObject',
            default: '/src/object'
        }
    },
    type: 'object',
    required: [
        'name',
        'description'
    ],
    title: 'TrackingObjectUpdate'
} as const;

export const TrackingObjectsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/TrackingObjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'TrackingObjectsPublic'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        description: {
            type: 'string',
            maxLength: 255,
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'email',
        'description'
    ],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 255,
            minLength: 8,
            title: 'Password'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'email',
        'password',
        'name'
    ],
    title: 'UserRegister'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
