// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { CreateObjectApiV1MonitoringObjectPostData, CreateObjectApiV1MonitoringObjectPostErrors, CreateObjectApiV1MonitoringObjectPostResponses, CreateUserApiV1UsersPostData, CreateUserApiV1UsersPostErrors, CreateUserApiV1UsersPostResponses, DeleteObjectApiV1MonitoringObjectIdDeleteData, DeleteObjectApiV1MonitoringObjectIdDeleteErrors, DeleteObjectApiV1MonitoringObjectIdDeleteResponses, LoginAccessTokenApiV1LoginAccessTokenPostData, LoginAccessTokenApiV1LoginAccessTokenPostErrors, LoginAccessTokenApiV1LoginAccessTokenPostResponses, ReadObjectApiV1MonitoringObjectIdGetData, ReadObjectApiV1MonitoringObjectIdGetErrors, ReadObjectApiV1MonitoringObjectIdGetResponses, ReadObjectsApiV1MonitoringObjectsGetData, ReadObjectsApiV1MonitoringObjectsGetErrors, ReadObjectsApiV1MonitoringObjectsGetResponses, ReadUserMeApiV1UsersMeGetData, ReadUserMeApiV1UsersMeGetResponses, TestTokenApiV1LoginTestTokenPostData, TestTokenApiV1LoginTestTokenPostResponses, UpdateObjectApiV1MonitoringObjectIdPutData, UpdateObjectApiV1MonitoringObjectIdPutErrors, UpdateObjectApiV1MonitoringObjectIdPutResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class LoginService {
    /**
     * Login Access Token
     *
     * OAuth2 compatible token login, get an access token for future requests
     */
    public static loginAccessTokenApiV1LoginAccessTokenPost<ThrowOnError extends boolean = false>(options: Options<LoginAccessTokenApiV1LoginAccessTokenPostData, ThrowOnError>) {
        return (options.client ?? client).post<LoginAccessTokenApiV1LoginAccessTokenPostResponses, LoginAccessTokenApiV1LoginAccessTokenPostErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            url: '/api/v1/login/access-token',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options.headers
            }
        });
    }
    
    /**
     * Test Token
     *
     * Test access token
     */
    public static testTokenApiV1LoginTestTokenPost<ThrowOnError extends boolean = false>(options?: Options<TestTokenApiV1LoginTestTokenPostData, ThrowOnError>) {
        return (options?.client ?? client).post<TestTokenApiV1LoginTestTokenPostResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/login/test-token',
            ...options
        });
    }
}

export class UsersService {
    /**
     * Read User Me
     */
    public static readUserMeApiV1UsersMeGet<ThrowOnError extends boolean = false>(options?: Options<ReadUserMeApiV1UsersMeGetData, ThrowOnError>) {
        return (options?.client ?? client).get<ReadUserMeApiV1UsersMeGetResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Create User
     */
    public static createUserApiV1UsersPost<ThrowOnError extends boolean = false>(options: Options<CreateUserApiV1UsersPostData, ThrowOnError>) {
        return (options.client ?? client).post<CreateUserApiV1UsersPostResponses, CreateUserApiV1UsersPostErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/users/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class MonitoringService {
    /**
     * Create Object
     */
    public static createObjectApiV1MonitoringObjectPost<ThrowOnError extends boolean = false>(options: Options<CreateObjectApiV1MonitoringObjectPostData, ThrowOnError>) {
        return (options.client ?? client).post<CreateObjectApiV1MonitoringObjectPostResponses, CreateObjectApiV1MonitoringObjectPostErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/monitoring/object',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Object
     */
    public static deleteObjectApiV1MonitoringObjectIdDelete<ThrowOnError extends boolean = false>(options: Options<DeleteObjectApiV1MonitoringObjectIdDeleteData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteObjectApiV1MonitoringObjectIdDeleteResponses, DeleteObjectApiV1MonitoringObjectIdDeleteErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/monitoring/object/{id}',
            ...options
        });
    }
    
    /**
     * Read Object
     */
    public static readObjectApiV1MonitoringObjectIdGet<ThrowOnError extends boolean = false>(options: Options<ReadObjectApiV1MonitoringObjectIdGetData, ThrowOnError>) {
        return (options.client ?? client).get<ReadObjectApiV1MonitoringObjectIdGetResponses, ReadObjectApiV1MonitoringObjectIdGetErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/monitoring/object/{id}',
            ...options
        });
    }
    
    /**
     * Update Object
     */
    public static updateObjectApiV1MonitoringObjectIdPut<ThrowOnError extends boolean = false>(options: Options<UpdateObjectApiV1MonitoringObjectIdPutData, ThrowOnError>) {
        return (options.client ?? client).put<UpdateObjectApiV1MonitoringObjectIdPutResponses, UpdateObjectApiV1MonitoringObjectIdPutErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/monitoring/object/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Read Objects
     */
    public static readObjectsApiV1MonitoringObjectsGet<ThrowOnError extends boolean = false>(options?: Options<ReadObjectsApiV1MonitoringObjectsGetData, ThrowOnError>) {
        return (options?.client ?? client).get<ReadObjectsApiV1MonitoringObjectsGetResponses, ReadObjectsApiV1MonitoringObjectsGetErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/monitoring/objects',
            ...options
        });
    }
}
