// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * Body_login_access_token_api_v1_login_access_token_post
 */
export type BodyLoginAccessTokenApiV1LoginAccessTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IconsObject
 */
export type IconsObject = '/src/object' | '/src/person' | '/src/bike' | '/src/scooter' | '/src/bus' | '/src/car' | '/src/tractor' | '/src/harvester' | '/src/airplane';

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TrackingObjectCreate
 */
export type TrackingObjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    icon_object?: IconsObject;
};

/**
 * TrackingObjectPublic
 */
export type TrackingObjectPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    icon_object?: IconsObject;
    /**
     * Signal
     */
    signal: number;
    /**
     * Position Lat
     */
    position_lat: number | string | null;
    /**
     * Position Lon
     */
    position_lon: number | string | null;
};

/**
 * TrackingObjectUpdate
 */
export type TrackingObjectUpdate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    icon_object?: IconsObject;
};

/**
 * TrackingObjectsPublic
 */
export type TrackingObjectsPublic = {
    /**
     * Data
     */
    data: Array<TrackingObjectPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Description
     */
    description: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Name
     */
    name: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
    body: BodyLoginAccessTokenApiV1LoginAccessTokenPost;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginAccessTokenApiV1LoginAccessTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostError = LoginAccessTokenApiV1LoginAccessTokenPostErrors[keyof LoginAccessTokenApiV1LoginAccessTokenPostErrors];

export type LoginAccessTokenApiV1LoginAccessTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse = LoginAccessTokenApiV1LoginAccessTokenPostResponses[keyof LoginAccessTokenApiV1LoginAccessTokenPostResponses];

export type TestTokenApiV1LoginTestTokenPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type TestTokenApiV1LoginTestTokenPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type TestTokenApiV1LoginTestTokenPostResponse = TestTokenApiV1LoginTestTokenPostResponses[keyof TestTokenApiV1LoginTestTokenPostResponses];

export type ReadUserMeApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ReadUserMeApiV1UsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserMeApiV1UsersMeGetResponse = ReadUserMeApiV1UsersMeGetResponses[keyof ReadUserMeApiV1UsersMeGetResponses];

export type CreateUserApiV1UsersPostData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type CreateUserApiV1UsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1UsersPostError = CreateUserApiV1UsersPostErrors[keyof CreateUserApiV1UsersPostErrors];

export type CreateUserApiV1UsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type CreateUserApiV1UsersPostResponse = CreateUserApiV1UsersPostResponses[keyof CreateUserApiV1UsersPostResponses];

export type CreateObjectApiV1MonitoringObjectPostData = {
    body: TrackingObjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/monitoring/object';
};

export type CreateObjectApiV1MonitoringObjectPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateObjectApiV1MonitoringObjectPostError = CreateObjectApiV1MonitoringObjectPostErrors[keyof CreateObjectApiV1MonitoringObjectPostErrors];

export type CreateObjectApiV1MonitoringObjectPostResponses = {
    /**
     * Successful Response
     */
    200: TrackingObjectPublic;
};

export type CreateObjectApiV1MonitoringObjectPostResponse = CreateObjectApiV1MonitoringObjectPostResponses[keyof CreateObjectApiV1MonitoringObjectPostResponses];

export type DeleteObjectApiV1MonitoringObjectIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/monitoring/object/{id}';
};

export type DeleteObjectApiV1MonitoringObjectIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteObjectApiV1MonitoringObjectIdDeleteError = DeleteObjectApiV1MonitoringObjectIdDeleteErrors[keyof DeleteObjectApiV1MonitoringObjectIdDeleteErrors];

export type DeleteObjectApiV1MonitoringObjectIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: TrackingObjectPublic;
};

export type DeleteObjectApiV1MonitoringObjectIdDeleteResponse = DeleteObjectApiV1MonitoringObjectIdDeleteResponses[keyof DeleteObjectApiV1MonitoringObjectIdDeleteResponses];

export type ReadObjectApiV1MonitoringObjectIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/monitoring/object/{id}';
};

export type ReadObjectApiV1MonitoringObjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadObjectApiV1MonitoringObjectIdGetError = ReadObjectApiV1MonitoringObjectIdGetErrors[keyof ReadObjectApiV1MonitoringObjectIdGetErrors];

export type ReadObjectApiV1MonitoringObjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: TrackingObjectPublic;
};

export type ReadObjectApiV1MonitoringObjectIdGetResponse = ReadObjectApiV1MonitoringObjectIdGetResponses[keyof ReadObjectApiV1MonitoringObjectIdGetResponses];

export type UpdateObjectApiV1MonitoringObjectIdPutData = {
    body: TrackingObjectUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/monitoring/object/{id}';
};

export type UpdateObjectApiV1MonitoringObjectIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateObjectApiV1MonitoringObjectIdPutError = UpdateObjectApiV1MonitoringObjectIdPutErrors[keyof UpdateObjectApiV1MonitoringObjectIdPutErrors];

export type UpdateObjectApiV1MonitoringObjectIdPutResponses = {
    /**
     * Successful Response
     */
    200: TrackingObjectPublic;
};

export type UpdateObjectApiV1MonitoringObjectIdPutResponse = UpdateObjectApiV1MonitoringObjectIdPutResponses[keyof UpdateObjectApiV1MonitoringObjectIdPutResponses];

export type ReadObjectsApiV1MonitoringObjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/monitoring/objects';
};

export type ReadObjectsApiV1MonitoringObjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadObjectsApiV1MonitoringObjectsGetError = ReadObjectsApiV1MonitoringObjectsGetErrors[keyof ReadObjectsApiV1MonitoringObjectsGetErrors];

export type ReadObjectsApiV1MonitoringObjectsGetResponses = {
    /**
     * Successful Response
     */
    200: TrackingObjectsPublic;
};

export type ReadObjectsApiV1MonitoringObjectsGetResponse = ReadObjectsApiV1MonitoringObjectsGetResponses[keyof ReadObjectsApiV1MonitoringObjectsGetResponses];
